# Generated by Django 4.2.21 on 2025-08-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.DeleteModel(
            name='Ad',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Rubric',
        ),
    ]
