# Generated by Django 4.2.21 on 2025-08-27 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0004_ad_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='image',
        ),
    ]
