# Generated by Django 4.2.21 on 2025-06-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_quiz_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
