# Generated by Django 4.2.21 on 2025-07-02 11:24

from django.db import migrations, models
import precise_bbcode.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='_content_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=precise_bbcode.fields.BBCodeTextField(default='', help_text='Используйте BBCode: [b], [i], [url], [quote]…[/quote] и др.', no_rendered_field=True, verbose_name='Содержимое (BBCode)'),
        ),
    ]
