# Generated by Django 4.2.21 on 2025-07-02 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post__content_rendered_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='_content_rendered',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
