# Generated by Django 4.2.21 on 2025-07-02 15:41

from django.db import migrations, models
import precise_bbcode.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_post__content_rendered_remove_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='_content_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=precise_bbcode.fields.BBCodeTextField(default='', no_rendered_field=True),
        ),
    ]
