# Generated by Django 4.2.21 on 2025-06-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'Заказ'},
        ),
    ]
