# Generated by Django 4.2.21 on 2025-08-09 23:45

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_document_photo_staticpick'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoResized',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', easy_thumbnails.fields.ThumbnailerImageField(upload_to='photos_resized/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
