# Generated by Django 4.2.21 on 2025-08-21 19:15

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_photoresized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoresized',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='photoresized',
            name='picture',
        ),
        migrations.AddField(
            model_name='photoresized',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='photoresized',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
